### ISSUE TITLE
Port app to Fabric

### ISSUE THREAD

**Issue by chrisglein** [chrisglein/artificial-chat#119]
### Summary

Started with this as a basis: https://github.com/chiaramooney/sample-fabric
But in 0.73+ this is now replaced with the official app template: https://github.com/microsoft/react-native-windows/wiki/Using-the-new-architecture-templates

# Plan
- [x] Stubbed out all dependencies
- [x] Made a quick JS-only implementation of `Picker` and `Popup`
- [x] Try to bring in the JS-only dependencies (to get `Markdown` working again, for example)
- [x] Take a crack at local native code (version info, but not on UWP) - need to learn about Fabric codegen?
- [x] Non-UWP alternatives for other non-UI module dependencies ([If needed?](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api))
  - [x] Modify min Fabric app sample to be packaged? Should get access to _some_ of the UWP-style APIs? (e.g. [Clipboard via DataTransfer](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.clipboard?view=winrt-22621#windows-requirements))
  - [x] `Clipboard`
    - [x] Local workaround
    - [x] Restore use of "@react-native-clipboard/clipboard"
  - [x] `AsyncStorage`
    - [x] Restore use of "@react-native-async-storage/async-storage"
  - [ ] `react-native-winrt` (for Speech Synthesis)
    - [x] ⚠️Workaround (switched from codegenJS to turbo module)
- [ ] UI module dependencies
  - [ ] Picker
    - [x] ⚠️Workaround (recreated a Picker replacement using `Modal`)
    - [ ] Restore use of "@react-native-picker/picker"
  - [ ] fluent-ui-reactnative
    - [x] ⚠️Workaround: Created FluentControls library in app with JS replacements
    - [ ] Figure out blocking issues with FURN
  - [ ] react-native-content-dialog (JS only)
    - [x] ⚠️Workaround: Local package patch of `PlatformColor` usage, changing color string constants
    - [ ] Figure out how module can have different versions for Fabric vs. Paper
  - [ ] react-native-syntax-highlighter (JS only)
    - [x] ⚠️Workaround: Removed
    - [ ] Figure out how to get working again
- [x] Identify the key gaps in what it's implemented for RNW Fabric thus far
- [x] Copy app `.png` assets to `.ico` files
- [ ] Release Fabric version of app to store

# Issues Found
- [x] https://github.com/microsoft/react-native-windows/issues/11452 Typing produces double keypresses
- [x] https://github.com/microsoft/react-native-windows/issues/11456 Button text does not render
- [x] https://github.com/microsoft/react-native-windows/issues/11456 Button background/border does not render
- [x] https://github.com/microsoft/react-native-windows/issues/11486 Caret in wrong position
- [x] https://github.com/microsoft/react-native-windows/issues/11549 Bottom border doesn't render
- [x] https://github.com/microsoft/react-native-windows/issues/11564 Need to run Metro in the meantime
- [x] https://github.com/microsoft/react-native-windows/issues/11763 Chat entry has no background plate (will be a difference between Paper and Fabric)
- [x] https://github.com/microsoft/react-native-windows/issues/11764
- [ ] Accessibility headers/groups not showing in Accessibility Insights
- [ ] Invoke pattern on button components does not invoke them (may need app side to use [`onAccessibilityTap`](https://reactnative.dev/docs/accessibility#onaccessibilitytap))
- [x] https://github.com/microsoft/react-native-windows/issues/12075 `ScrollView` does not display a scroll bar
- [x] https://github.com/microsoft/react-native-windows/issues/12076 `ScrollView` cannot be controlled with keyboard events (page up, page down, home, end)
- [ ] https://github.com/microsoft/react-native-windows/issues/11489 Components do not respond to dark mode
- [x] https://github.com/microsoft/react-native-windows/issues/12786

# Not Yet Implemented
- [x] https://github.com/microsoft/react-native-windows/issues/11457
- [x] https://github.com/microsoft/react-native-windows/issues/11458
- [x] https://github.com/microsoft/react-native-windows/issues/11459
- [x] https://github.com/microsoft/react-native-windows/issues/11460
- [x] https://github.com/microsoft/react-native-windows/issues/11461
- [x] https://github.com/microsoft/react-native-windows/issues/11462
- [x] https://github.com/microsoft/react-native-windows/issues/12074

# Screenshot of In-Progress Implementation
![artificialChatOnFabric](https://user-images.githubusercontent.com/26607885/230462879-0e6e976b-58e2-4c33-a08f-f7cd59c52d93.png)

**Comment by chrisglein** [comment]
That previous set of screenshots was across 2 different machines with different resolutions. Here's a more apples to apples comparison (both running side by side on same dev box):

| Paper | Fabric |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/26607885/234415792-179777b3-006c-4ae0-9221-bd1ec42466d0.png) | ![image](https://user-images.githubusercontent.com/26607885/234415769-d959e87d-a2ff-42a2-adc6-23010f207f15.png) |

**Comment by acoates-ms** [comment]
Are we missing a border in those tables? (The horizontal lines)  Any idea what that is?  I thought our border implementation on fabric is actually more complete than the paper one.

**Comment by chrisglein** [comment]
> Are we missing a border in those tables? (The horizontal lines) Any idea what that is? I thought our border implementation on fabric is actually more complete than the paper one.

Yeah, I had noticed that one but haven't had a chance to dig in yet. I'm using a JS-only module for markdown rendering, and the styling for those tables should be [here](https://github.com/iamacup/react-native-markdown-display/blob/master/src/lib/styles.js#L133). That table element is using `borderBottomWidth`. So it appears that in Fabric the `borderBottomWidth` isn't registering. It's marked as completed in [the table](https://github.com/microsoft/react-native-windows/issues/11136), so I assume there's a bug somewhere in the handling. I'll poke around and open a bug to track this.

**Comment by chrisglein** [comment]
Would probably be possible to merge this sooner if there was the ability to have file redirects for fabric components. Example: mycomponent.windows.fabric.js.

**Comment by chrisglein** [comment]
Grabbing the latest Canary build with some fixes that have happened, the addition of color emojis is great. Accessibility information is starting to come online too, so we can start looking at those gaps.

| Paper | Fabric |
|--------|--------|
| ![image](https://github.com/chrisglein/artificial-chat/assets/26607885/501c774a-c404-4d6b-82b4-a77a0337f941)| ![image](https://github.com/chrisglein/artificial-chat/assets/26607885/a58a5372-3b92-43d2-ac27-d23eac2b9eb6)| 
| ![image](https://github.com/chrisglein/artificial-chat/assets/26607885/bbdd9966-208a-4a75-b395-859856922f00) | ![image](https://github.com/chrisglein/artificial-chat/assets/26607885/1a0e3479-3004-43ef-8a10-26a30c265af4) |

**Comment by chrisglein** [comment]
Brought in latest canary (761) and we have a working scrollbar now:
![image](https://github.com/chrisglein/artificial-chat/assets/26607885/911ec0a7-40ba-45c9-9787-e58ee6fa812f)

**Comment by chrisglein** [comment]
At this point the PR to migrate main from Paper to Fabric has been merged (https://github.com/chrisglein/artificial-chat/pull/120) 🎉. Capturing some details about the final steps of the journey here.

# Changes Needed to App

### Replaced react-native-picker with custom component using Modal
At some point Picker will be ready (and will host the native WinUI3 `ComboBox` control), but I couldn't wait. It's a relatively straightforward control to [replicate](https://github.com/chrisglein/artificial-chat/pull/160), ignoring matching all the niceties of native visual styling. Modal is currently a bit finicky still in its styling ([#15169](https://github.com/microsoft/react-native-windows/issues/15169)), sizing ([#14805](https://github.com/microsoft/react-native-windows/issues/14805)), and placement. But what I have is functional.

This is temporary and react-native-picker usage should be restored in the app in the coming months, whenever it is available again.

### Removed syntax highlighting
The syntax highlighting module I was using seems to be incompatible with Fabric, and module isn't actively maintained so the safest bet was to move off of it. This is a regression in functionality, but not a major one.

I can return to restore this later, it just needs some detective work.

### Removed fluentui-react-native
I created a mock implementation to work around Fabric incompatibility with fluentui-react-native. This module only lightly supported Windows before, and not out of the box (there were already in-app workarounds, see #114 ). In the meantime I've replicated its Button/CheckBox/Hyperlink styles myself within the app.

This can only be restored if FURN itself is patched; maintaining the patches to it in this repro isn't really sustainable. It may be better to prioritize other individual modules for getting the right visual styling here. In the meantime, in-app styling for these controls is actually just fine

### Removed react-native-winrt
This module was used to easily access the Speech Synthesis APIs for #144. Right no react-native-winrt does not support Fabric and RNW on Win32. It almost certain could with some work, but it's not there today. So I removed it and replaced it with the equivalent native code, which was a change Copilot was able to handle pretty easily ([see commit](https://github.com/chrisglein/artificial-chat/pull/120/commits/a68473090f83bd87b5b1a05ae8fc4a662a27abc4)).

It's okay the way it is, but it would be more ideal to remove the code and lean on react-native-winrt when it is available.

### Styling
- TextInput no longer displays a background layer (parity with RN core). Solution: Create a simple FluentTextInput component that adds the visual styling and forwards the bulk of the functionality to TextInput
- Text no longer does dark theme styling out of the box (parity with RN core). Solution: All Text elements must be styled (and the style implementation uses PlatformColor to be dark mode aware)
- Not all PlatformColor values usable on Paper are valid on Fabric. This required a deep review of the app's behavior on light and dark mode to update to Fabric values or move color styling into the app's style table

### Accessibility
- Button clicks are not wired up to accessibility invoke providers by default (parity with RN core). Solution: Hook up onAccessibilityTap for all buttons

### Popups
There is no Windows-only `Flyout` and `Popup` component like there was in Paper. But there is `Modal`. The behavior on Windows is that of a separate child window, which has some undesirable changes in behavior (see bugs below). And there is no built in "light dismiss" functionality. This required various workarounds.

# More Bugs Found
Being on the cutting edge of platform readiness means uncovering bugs. Which then get fixed. It's magic! Here's the latest found during the last leg of conversion:
- https://github.com/microsoft/react-native-windows/issues/14805 this resulted in significant workarounds of fixed sizes
- https://github.com/microsoft/react-native-windows/issues/15169 this would improve the integrated feel of the app if fixed
- https://github.com/microsoft/react-native-windows/issues/15158 by design, but not sufficiently documented)
- https://github.com/microsoft/react-native-windows/issues/15159
- https://github.com/microsoft/react-native-windows/issues/15160 better than Paper in some ways, but still incorrect behavior
- https://github.com/microsoft/react-native-windows/issues/15165 this one is high impact and will block properly updating the store release
- https://github.com/microsoft/react-native-windows/issues/15166 
- https://github.com/microsoft/react-native-windows/issues/15167 
- https://github.com/microsoft/react-native-windows/issues/15168 easy to work around, but did require changing Paper JS
- https://github.com/microsoft/react-native-windows/issues/15177

# Performance 

The closest of an apples-to-apples comparison of what working set looks like. This is walking through the same scenario, but due to the variable nature of AI responses the visible results are different.

| Paper| Fabric |
|--------|--------|
| Private working set: 72,220K | Private working set: 57,500K |
| <img width="917" height="1048" alt="Image" src="https://github.com/user-attachments/assets/10fd0984-1436-4987-ad6d-fc8a3c706c1f" /> | <img width="1151" height="1286" alt="Image" src="https://github.com/user-attachments/assets/637dd46e-167f-41a6-9198-8e76e3d9d333" /> |

So in rough terms, about a 20% reduction in private working set.

I haven't looked at time to first render of anything like that.
